import './globals.css';
import type { Metadata } from 'next';
import { Urbanist, Raleway, DM_Sans } from 'next/font/google';
import { ThemeProvider } from '@/components/ui/theme-provider';

const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  variable: '--display-font',
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--body-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <main className="font-body">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
