import './globals.css';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Providers from '@/providers/Providers';
import getQueryClient from '@/lib/getQueryClient';
import { HydrationBoundary, dehydrate } from '@tanstack/react-query';
import prefetchCurrentSession from '@/requests/prefetch/prefetchCurrentSession';

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--body-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  await prefetchCurrentSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.variable}`}>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <main>{children}</main>
          </HydrationBoundary>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
